#version 450

layout (binding = 0,rgba32f) uniform readonly image2D inputImage;
layout (binding = 1,rgba32f) uniform writeonly image2D outputImage;
layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


void main() {

    ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);

    vec3 inColor = imageLoad(inputImage, texCoord).rgb;


    vec3 outColor = inColor;


    imageStore(outputImage, texCoord, vec4(outColor,1));
}